const express    = require('express');
const cors       = require('cors');
const bodyParser = require('body-parser');
const path       = require('path');
const app = express();
app.use(cors({ origin: '*' }));
app.use(bodyParser.json());
app.use(express.static(path.join(__dirname, '../public')));
app.get('/api/ping', (req, res) => res.json({ ok: true }));
app.get('/api/medicines',           (req, res) => res.json([]));
app.post('/api/medicines',          (req, res) => res.status(201).json(req.body));
app.delete('/api/medicines/:id',    (req, res) => res.json({ success: true }));
app.delete('/api/medicines',        (req, res) => res.json({ success: true }));
app.get('/api/history',             (req, res) => res.json([]));
app.post('/api/history',            (req, res) => res.status(201).json(req.body));
app.delete('/api/history',          (req, res) => res.json({ success: true }));
app.get('/api/status',              (req, res) => res.json({ total:0, taken:0, missed:0, upcoming:0, medicines:[] }));
app.get('/api/alarms/due',          (req, res) => res.json([]));
app.get('/api/calendar/:date',      (req, res) => res.json({ date: req.params.date, medicines: [] }));
app.get('/api/calendar/month/:y/:m',(req, res) => res.json({ overview: {} }));
app.get('*', (req, res) => res.sendFile(path.join(__dirname, '../public/index.html')));
module.exports = app;
